/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include "main.h"
#include "led.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void init_tasks_stack(void);
void enable_processor_faults(void);
void update_next_task(void);
void save_psp_value(uint32_t current_psp_value);
__attribute__((naked)) void switch_sp_to_psp(void);
void init_systick_timer(uint32_t tick_hz);

void idle_handler(void);//this is idle task
void task1_handler(void);//this is task 1
void task2_handler(void);//this is task 2
void task3_handler(void);//this is task 3
void task4_handler(void);//this is the task 4

void schedule(void);
void unblock_tasks(void);
void update_global_tick_count(void);

void SysTick_Handler(void);
__attribute__((naked)) void init_schedular_stack(uint32_t sched_top_of_stack);

void task_delay(uint32_t tick_count);

uint8_t current_task = 0;//idle task is running initially
uint32_t g_tick_count =0;

typedef struct{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handlers)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	//
	enable_processor_faults();

	init_schedular_stack(SCHED_STACK_START);

	init_tasks_stack();//task stack init and to store dummy stack frames
	led_init_all();
	init_systick_timer(TICK_HZ);
	/*---------------------stack using psp-------------------*/

	switch_sp_to_psp();
	idle_handler();
    /* Loop forever */
	for(;;);
}
void idle_handler(void)
{
	while(1);
}
void task1_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
		printf("in Task 1\n");
	}

}
void task2_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
		printf("in Task 2\n");
	}
}
void task3_handler(void)
{
	while(1)
	{
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
		printf("in Task 3\n");
	}
}
void task4_handler(void)
{
	while(1)
	{

		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
		printf("in Task 4\n");
	}

}
void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t *)0xE000E014;
	uint32_t *pSCSR = (uint32_t *)0xE000E010;
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;

	//clear the value of SVR
	*pSRVR &= ~(0x00FFFFFF);

	//load the value in to the svr
	*pSRVR |= count_value;

	//settings
	*pSCSR |= (1<<1); // Enables SysTick exception request:
	*pSCSR |= (1<<2); // Indicates the clock source , processor clock source

	//enable systick
	*pSCSR |= (1<<0); //enables the counter
}
__attribute__((naked)) void init_schedular_stack(uint32_t sched_top_of_stack)
{
	__asm volatile("MSR MSP,%0"::"r"(sched_top_of_stack) : );
	__asm volatile("BX LR");//this stores the adress of link register BX is Branch indirect

}



void init_tasks_stack(void)
{
	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handlers = idle_handler;
	user_tasks[1].task_handlers = task1_handler;
	user_tasks[2].task_handlers = task2_handler;
	user_tasks[3].task_handlers = task3_handler;
	user_tasks[4].task_handlers = task4_handler;

	uint32_t *pPsp;
	for(int i=0;i < MAX_TASKS;i++)
	{
		pPsp = (uint32_t *)user_tasks[i].psp_value;
		pPsp--;
		*pPsp = DUMMY_XPSR;//0x00100000;
		pPsp--;//PC
		*pPsp = (uint32_t)user_tasks[i].task_handlers;
		pPsp--;//LR
		*pPsp = 0xFFFFFFFD;

		for(int j = 0;j < 13;j++)
		{
			pPsp--;
			*pPsp = 0;
		}

		user_tasks[i].psp_value = (uint32_t)pPsp;

	}
}
void enable_processor_faults(void)
{
	//1.enable faults
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1<<16);//mem manage
	*pSHCSR |= (1<<17);//bus fault
	*pSHCSR |= (1<<18);//usage fault

}
void schedule(void)
{
	uint32_t *pICSR = (uint32_t*)0XE000ED04;
	*pICSR |= (1 << 28);
}

void task_delay(uint32_t tick_count)
{
	//before disable interrupt
	INTERRUPT_DISABLE();
	if(current_task)
	{
	user_tasks[current_task].block_count = g_tick_count + tick_count;
	user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
	schedule();
	}
	//enable interupt
	INTERRUPT_ENABLE();
}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}
__attribute__((naked)) void switch_sp_to_psp(void)
{
	//1. initialize the PSP with TASK1 stack register
		//get the value of psp of current task
		__asm volatile("PUSH {LR}"); // preserve lr which holds return to main
		__asm volatile ("BL get_psp_value");
		__asm volatile ("MSR PSP,R0");//initialize psp
		__asm volatile ("POP {LR}"); // pop backs to lr value
	//2.change SP to PSP using control register
	__asm volatile ("MOV R0,#0x02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");

}
void save_psp_value(uint32_t current_psp_value)
{
	user_tasks[current_task].psp_value = current_psp_value;
}
void update_next_task(void)
{
	int state = TASK_BLOCKED_STATE;
	for(int i=0;i< (MAX_TASKS);i++)
	{
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if( (state == TASK_READY_STATE) && (current_task != 0) )
		break;
	}
	if(state != TASK_READY_STATE)
		current_task = 0;
}

__attribute__((naked)) void PendSV_Handler(void)
{
		/* save the context of current task */
		//1.get currrent running tasks psp value
		__asm volatile("MRS R0,PSP");
		//2.using that psp value store sf2 (R4 to R11)
		__asm volatile("STMDB R0!,{R4-R11}");
		__asm volatile("PUSH {LR}");
		//3. save the current value of Psp
		__asm volatile ("BL save_psp_value");

	/*Retrive the context of next task */
		//1. Decide next task to run
		__asm volatile("BL update_next_task");
		//2. get its past Psp value
		__asm volatile("BL get_psp_value");
		//3. using that Psp value retrive SF2 (R4 to R11)
		__asm volatile("LDMIA R0!,{R4-R11}");
		//4. update Psp and exit
		__asm volatile("MSR PSP,R0");

		__asm volatile("POP {LR}");

		__asm volatile("BX LR");

}
void update_global_tick_count(void)
{
	g_tick_count++;
}
void unblock_tasks(void)
{
	for(int i=1;i < MAX_TASKS;i++)
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(user_tasks[i].block_count == g_tick_count)
			{
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}
void SysTick_Handler(void)
{
	uint32_t *pICSR = (uint32_t*)0XE000ED04;
	update_global_tick_count();
	unblock_tasks();
	/*--------Pends the pendSV Exception-----*/
	*pICSR |= (1 << 28);
}
//2.Implement fault handlers
void BusFault_Handler(void)
{
	while(1);
}
void MemManage_Handler(void)
{
	while(1);
}
void UsageFault_Handler(void)
{
	while(1);
}
